#!/bin/sh
set -e

if [ -z "${1}" ]; then
        echo "usage: $0 package.tbz2"
        echo "example: $0 ssh-mtconfig-4.0.4.tbz2"
        exit
fi

banner() {
echo "================================================================"
echo "$1"
echo "================================================================"
}

banner "Create the workdir, tbz2file"
WORKDIR="/tmp/$(date +%Y%m%d_%H%M%S)"
PACKAGE_LIST=""
for package_path in "$@"
do
	TBZ2FILE="$(basename "${package_path}")"
	TBZ2FILE_XPAK="$(echo "$TBZ2FILE" | sed -e 's/\.tbz2/\.xpak/g')"
	echo "TBZ2FILE=$TBZ2FILE"
	echo "TBZ2FILE_XPAK=$TBZ2FILE_XPAK"
	echo "WORKDIR=$WORKDIR"
	mkdir -pv "${WORKDIR}"

	banner "Copying the file to the workdir"
	cp -v "${package_path}" "${WORKDIR}"

	banner "Uncompressing the tbz2file"
	qtbz2 -x -O "${WORKDIR}/${TBZ2FILE}" > "${WORKDIR}/${TBZ2FILE_XPAK}"
	PF="$(qxpak -O -x "${WORKDIR}/${TBZ2FILE_XPAK}" PF)"
	CATEGORY="$(qxpak -O -x "${WORKDIR}/${TBZ2FILE_XPAK}" CATEGORY)"
	echo "PF=$PF"
	echo "CATEGORY=$CATEGORY"
	echo "TBZ2FILE_XPAK=$TBZ2FILE_XPAK"

	banner "Copying $TBZ2FILE in the PKGDIR"
	MYPKGDIR="${WORKDIR}/All"
	mkdir -pv "${MYPKGDIR}"
	cp -v "${WORKDIR}/${TBZ2FILE}" "${MYPKGDIR}"
	PACKAGE_LIST="$PACKAGE_LIST =${CATEGORY}/${PF}"
done
PKGDIR=${WORKDIR} emerge -K $PACKAGE_LIST
